server:
  port: 8083

spring:
  data:
    mongodb:
      database: Bootcamp32
      host: localhost
      port: 27017

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8086/eureka/